### ISSUE TITLE
Lexical Model for text prediction

### ISSUE THREAD

**Issue by trosel** [Runeboard/Runeboard-Ogham#2]
This issue is to track the steps needed to add a lexical model for text prediction:

https://help.keyman.com/DEVELOPER/12.0/guides/lexical-models/intro/

I believe that Keyman makes this fairly easy. Just need to get a word list for English in order of frequency. Perhaps the easiest way to do this would be to copy the one from Shavian and just convert that to Runes.

The [Shavian list is fairly global in spelling](https://readlex.pythonanywhere.com/spellingprinciples/), although it leans towards RP. 

One could have both `en-Runr-US` and `en-Runr-UK` perhaps though. I'm not sure if Keyman lets the user decide which model they want to use.

**Comment by Runeboard** [comment]
Define "fairly easy". Have you added a lexical model for text prediction yourself before? Are you speaking from experience or hearsay?

We already have Oxford's CEFR and Cambridge's Vocabulary lists, but don't want to start too big because any updates then require major changes. This is one reason why we've been holding it.

Another important matter to remember is that runic spelling has always been flexible. The Touchstone is only intended to be a reference point to assist intelligibility across accents, not as a prescriptive spelling module. Though it could be helpful for faster typing, predictive text feature should not pressure users into conforming to any particular way of spelling.

Thank you for posting the link to the _Spelling principles for the Read Lexicon_. I'd lost that and way looking for it :)

**Comment by trosel** [comment]
>  Are you speaking from experience

I've read the documentation before and you just need a 2 column `.tsv` file. Column one is the word and column two is a number of the word frequency (highest is most frequent).

> We already have Oxford's CEFR and Cambridge's Vocabulary lists

Is your vocabulary list a "midatlantic" style? I assume it uses the LOT set, keeps the Rs and keeps the Yods? 

I agree that we don't want to pressure people btw. But I think (not totally certain) that the user can choose which file they use for predictive spelling. So their could be multiple files that each use a different spelling standard. May need to double check that with SIL though. 

It does help to have something like this to increase confidence in spelling. And saves time when chatting back and forth.

**Comment by Runeboard** [comment]
That sounds fairly straight forward. Thanks.

Oxford provides a few RP & Gen-Am lists. Cambridge only provides a list for English learners. There is an old but very detailed book for actors on the Mid-Atlantic accent which we've been meaning to obtain but it's not a priority at the moment.

SIL doesn't require a dictionary at all. If you compare the number of keyboards available with the number of lexical modules, you'll find the majority of languages don't have them.

Are you familiar with [1337](https://en.wikipedia.org/wiki/Leet)?

**Comment by trosel** [comment]
> SIL doesn't require a dictionary at all. If you compare the number of keyboards available with the number of lexical modules, you'll find the majority of languages don't have them.

Yes, the text prediction feature is totally optional. This little article explains why it's nice though: https://help.keyman.com/DEVELOPER/12.0/guides/lexical-models/intro/

I'm sure most of the Keyman keyboards don't have them because 90% of Keyman's keyboards are for minority languages and they are works in progress. It's why that app exists, basically. People don't use Keyman for mainstream languages like Spanish. But the goal of Keyman is to provide a user experience for minority languages that are *as good as* the mainstream languages in the native operating system keyboards. And part of that is to provide feature parity with features like text prediction.

> Are you familiar with [1337](https://en.wikipedia.org/wiki/Leet)?

Spelling words with numbers? Sure haha

**Comment by Runeboard** [comment]
Thanks for the link.

All major languages now have standarised spelling systems in their primary script. But even in spite of the Read Lexicon, there is no single 'correct' way of spelling in Shavian. Similarly, there is no correct way of spelling in runes. However, that has led to a vast array of spelling systems which are frequently unintelligible to anyone outside of their local user community. What we're proposing is a method for overcoming that problem so that runic texts can be understood by the global English-speaking community while still allowing for some degree of variation.

1337 is more than just spelling with numbers. It uses a variety of symbols too.

**Comment by trosel** [comment]
> What we're proposing is a method for overcoming that problem so that runic texts can be understood by the global English-speaking community while still allowing for some degree of variation.

Yep! I think that goal is totally agreeable with one or two dictionaries to help with text prediction still.

> 1337 is more than just spelling with numbers. It uses a variety of symbols too.

What is the relevance to this conversation?

**Comment by Runeboard** [comment]
Just as leet requires a degree of mental flexibility to decipher, so did all writing historically. How many 16th century works have you read? They contain plenty of words we still use but were once spelt in a variety of different ways, some of which are retained in modern Scots.

It's that natural flexibility which keeps written language as living and dynamic as spoken language. Once spelling becomes inflexible, it gradually atrophies. Eventually one ends up with a situation like Thai has with 44 characters representing 21 consonant phonemes. But English has historically suffered from the reverse problem more often, i.e. needing to use digraphs due to a lack of characters. My concern is that dictionaries foster rigidity. They encourage people to tell others their way of writing is not 'proper'. 

In the Commonwealth, teachers still spoke of 'Proper English' when I was in school. Using that term is now seen as oppressive so it's been replaced by 'Standard English'. While I'm generally not keen on political correctness, in this case I can see why they made the change. There are so many varieties of English, to imply that traditional RP is the only way to speak English properly is plainly absurd.

I want runes to be a script the ordinary man can claim as his own without having to worry about whether his spelling matches that used in the halls of academia. It's not easy to try and balance that with an attempt to make runes intelligible across dialects. To be fair, I can see why there are so many divergent ways of writing today's English in runes. Yet so long as that remains the case, efforts to revive runes will be bound to fail. I just hope to show the world there's a way that can work.

**Comment by trosel** [comment]
> My concern is that dictionaries foster rigidity. They encourage people to tell others their way of writing is not 'proper'.

I agree with that concern! That is why my dream is ultimately to have a dictionary that is closer to Wiktionary where we can list many spellings (pronunciations) for one word sense.

> I want runes to be a script the ordinary man can claim as his own without having to worry about whether his spelling matches that used in the halls of academia. 

To quote Steve Jobs, "a bicycle for the mind" 👍 🚲 🧠 

I'll just close this for now then. We can re-open later if someone else wants this
